# Linear Algebra with Python

This notebook is supposed to be a reference for solving linear algebra problems with Python. If you do not have any experience with Python, we suggest you do the Python Tutorials first!

## 1. Basics

In Python, we use the package `numpy` to represent Vectors and Matrices.

In [2]:
import numpy as np

### Create Vectors

We use an N-by-1 numpy array to represent a vector with N entries and a N-by-M array to reprent a matrix with N rows and M columns.

In [3]:
# create a vector
v = np.array([[1],[2],[3]])
print(v) # print the vector
print(v.shape) # print the shape of the vector

[[1]
 [2]
 [3]]
(3, 1)


### Create Matrices

In [4]:
# create a 3x3 matrix
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"\nA = {A}")
print(A.shape) # print the shape of the matrix

# create a Unit matrix
B = np.eye(3)
print(f"\nB = {B}")

# create a diagonal matrix
C = np.diag([1,10,100])
print(f"\nC = {C}")



A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

B = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

C = [[  1   0   0]
 [  0  10   0]
 [  0   0 100]]


### Addition and Subtraction

In [5]:
 # add A to C
result = A + C
print(f"\nA + C = {result}")

# subtract C from A
result = A - C 
print(f"\nA - C = {result}")


A + C = [[  2   2   3]
 [  4  15   6]
 [  7   8 109]]

A - C = [[  0   2   3]
 [  4  -5   6]
 [  7   8 -91]]


### Scalar Multiplication

In [6]:
# Multiply 3 with the matrix C
result = 3*C 
print(f"\n3*C = {result}")


3*C = [[  3   0   0]
 [  0  30   0]
 [  0   0 300]]


### Matrix Vector Multiplication

In [7]:
# multiply the matrix A with the vector v
result = A@v
print(f"\nAv = {result}")


Av = [[14]
 [32]
 [50]]


### Matrix-Matrix Multiplication 

In [8]:
# Compute the product ABC
result = A@B@C
print(f"\nABC = {result}")


ABC = [[  1.  20. 300.]
 [  4.  50. 600.]
 [  7.  80. 900.]]


## 2. Matrix and Vector Properties and Operations

### Solving a linear system

In [9]:
# solve the problem Cx = v
# compute the inverse of the Matrix C
result = np.linalg.solve(C,v)
print(f"\n The solution of Cx = v is \n x = {result}")


 The solution of Cx = v is 
 x = [[1.  ]
 [0.2 ]
 [0.03]]




### Inverse of a Matrix

In [10]:
# compute the inverse of the Matrix C
result = np.linalg.inv(C)
print(f"\ninv(C) = {result}")

# Some Matrices are not invertible, numpy will give a warning or an error
result = np.linalg.inv(np.diag([1,1,0]))
print(f"\ninv(CCA) = {result}")
 


inv(C) = [[1.   0.   0.  ]
 [0.   0.1  0.  ]
 [0.   0.   0.01]]


LinAlgError: Singular matrix

### Norm of a Vector

In [ ]:
# compute the 2-norm of v -  method 1
result = np.linalg.norm(v)
print(f"\nnorm2(v) = {result}")

# compute the 2-norm of v -  method 2
result = np.sqrt(v.T@v)
print(f"\nsqrt(v^T v) = {result}")

# compute the squared 2-norm of v
result = v.T@v
print(f"\n v^T v = {result}")

# compute the 1-norm of v
result = np.linalg.norm(v,1)
print(f"\nnorm1(v) = {result}")

# squared weighted norm of v, with weighting matrix C = diag([1,10,100])
result = v.T@C@v
print(f"\n v^T C v = {result}")


### Rank of a Matrix

In [ ]:
# Compute the Rank of the matrix A
result = np.linalg.matrix_rank(A)
print(f"\nrank(A) = {result}")

### Eigenvalues and Eigenvectors

In [ ]:
# compute the eigenvalues of A
lam, v = np.linalg.eig(A)
print(f"The eigenvalues of A are {lam}") 
print(f"and the corresponding eigenvectors are {v}")

### Plotting the deformation of a unit circle (needed?)